// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwbpbsyagyoytniidoah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3YnBic3lhZ3lveXRuaWlkb2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTA2ODcsImV4cCI6MjA2NzQ4NjY4N30.YXHJqlOUTxqUNyNog9W6tFWgYExrXEmbrBrEgbnF9Jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});